title: Latest
description: A centralized and publicly hosted sh script to install latest debian or rpm package
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
